### ISSUE TITLE
 Error: Could not authenticate request

### ISSUE THREAD

**Issue by ils-sapnaj** [googleapis/nodejs-storage#365]
#### Environment details

  - OS: Windows 10
  - Node.js version: 8.11.4
  - npm version: 5.6.0
  - `@google-cloud/storage` version: 1.7.0

#### Steps to reproduce
```js
var googleStorageCloud = require('@google-cloud/storage');
Object.prototype.GCP_upload_file=function (image_look_up_path, image_file_name, CLOUD_BUCKET, user_email, space, GCP_access_url, googleStorage, project_id,  callback)
{
       var fs = require("fs");
	var mime = require('mime-types')
	var mimetyp = mime.lookup(image_look_up_path);
	
			if (fs.existsSync(image_look_up_path))
			{
				console.log(JSON.stringify(googleStorageCloud));
				var storage = new googleStorageCloud
				({
				  projectId: 'XXXXXX',
				  keyFilename: './GCP_credential.json'
				})
				
				console.log(JSON.stringify(storage));
				var bucket = storage.bucket(CLOUD_BUCKET);
				var files = bucket.file(space+'/'+user_email+'/'+image_file_name);
				fs.createReadStream(image_look_up_path)
				.pipe(files.createWriteStream
				({
					metadata:
					{
					  contentType: mimetyp
					},
					predefinedAcl: "publicRead"
				}))
				.on("error", (err) =>
				{
					console.log("err : "+err);
				})
				.on('finish', () =>
				{
					console.log("url : "+`${GCP_access_url}${CLOUD_BUCKET}/${space}/${user_email}/${image_file_name}`);
				});
				return callback(null, `${GCP_access_url}${CLOUD_BUCKET}/${space}/${user_email}/${image_file_name}`);
			}
			
}
```
I am getting the following error when executing the above code  : 

```
undefined
{}
err : Error: Could not authenticate request
Request failed with status code 404
```

It is not authenticating me. I have tried for @google-cloud/storage 2.0.0 also then it is giving 
```
{}
TypeError: googleStorageCloud is not a function
    at Object.GCP_upload_file (D:\xxxx\routes\lib\constant.js:513:19)
    at Object.applyAndWait (D:\xxxxxx\node_modules\wait.for\waitfor.js:46:12)
    at Object.for (D:\xxxxxx\node_modules\wait.for\waitfor.js:62:21)
    at D:\xxxxxx\routes\v2.js:445:25
    at Array.map (<anonymous>)
    at D:\xxxxx\routes\v2.js:383:43
    at Array.map (<anonymous>)
    at handleGet (D:\xxxxx\routes\v2.js:346:34)
    at D:\xxxxx\node_modules\wait.for\waitfor.js:15:31
```

I have invested a whole day but nothing works. This code is running fine on node 6 and npm 4 but giving an error when I have upgraded the node version to 8.

Please help me to resolve this issue.

**Comment by fhinkel** [comment]
@ils-sapnaj Thanks so much for raising the issue! 

With 2.0.0, you have to use the following: 

`var {Storage} = require('@google-cloud/storage');`
 
If you want a specific variable name: 

`var googleStorageCloud = require('@google-cloud/storage').Storage;`

For the authentication problem, could you follow [these instructions](https://cloud.google.com/storage/docs/authentication) for Client library authentication? Can you authenticate using the code snippet provided for Node.js? Sometimes the environment variable `$GOOGLE_APPLICATION_CREDENTIALS` isn't set correctly.

**Comment by ils-sapnaj** [comment]
Thanks. It is working now.

**Comment by JustinBeckwith** [comment]
Greetings!  If it's working with 2.0, we're going to go ahead and close this out.  If you're still running into issues with the new release... please do let us know!

**Comment by ils-sapnaj** [comment]
Hi,

I am still getting the issue and error "Error: Could not authenticate request". Here is the system configuration : 

OS: Windows 10
Node.js version: 8.11.4
npm version: 5.6.0
@google-cloud/storage version: 2.0.3

It was working fine with node version 6.11.2 and npm version 3.10.10.

Please help me out, I can't work with node 6, I need to upgrade but google storage package is not working.

**Comment by JustinBeckwith** [comment]
Greetings @ils-sapnaj!  Can you please open a new issue?  Make sure to include the code you're using that leads to the error please :) Also - if you could share your package.json that would be *super* helpful.
