### ISSUE TITLE
download fails with TypeError: rawResponseStream.toJSON is not a function

### ISSUE THREAD

**Issue by edeustace** [googleapis/nodejs-storage#528]
#### Environment details

  - OS: pop-os
  - Node.js version: 9.11.2
  - npm version: 5.7.1
  - `@google-cloud/storage` version: >=2.2.0 (works in 2.1.0)

#### Steps to reproduce
```javascript
const { Storage } = require("@google-cloud/storage");
const s = new Storage();
const bucket = s.bucket("add-bucket-here");
const file = bucket.file("some-file-here.md");
file.download();
 ```
Expected: script runs successfully.
Actual: A TypeError occurs: 
```shell
TypeError: rawResponseStream.toJSON is not a function
    at onResponse (/node_modules/@google-cloud/storage/build/src/file.js:413:51)
    at Util.handleResp (/node_modules/@google-cloud/common/build/src/util.js:123:9)
    at Duplexify.requestStream.on.on.res (/node_modules/@google-cloud/storage/build/src/file.js:392:31)
    at Duplexify.emit (events.js:180:13)
    at DestroyableTransform.emit (events.js:180:13)
    at onResponse (/node_modules/retry-request/index.js:194:19)
    at PassThrough.<anonymous> (/node_modules/retry-request/index.js:149:11)
    at PassThrough.emit (events.js:180:13)
    at /node_modules/teeny-request/build/src/index.js:186:29
    at <anonymous>
```
Had a look in the debugger - and this stream has no such function, it has a `headers` object though?

This [commit][commit] fixes the issue. However I wouldn't be comfortable making a PR out of this because I'm casting to a `Readable` which may not always be the case?

[commit]: https://github.com/key-data-systems/nodejs-storage/commit/07705129a80a449d3a245641b744b46b52bca10b

**Comment by kinwa91** [comment]
We have a fix here: https://github.com/fhinkel/teeny-request/pull/32

**Comment by f5io** [comment]
@kinwa91 that update of [fhinkel/teeny-request](https://github.com/fhinkel/teeny-request) fixed me having the same issue. the speediness of the fix is much appreciated! :+1:

**Comment by JustinBeckwith** [comment]
Since this appears to be fixed - I'm going to go ahead and close this out for now.  If folks are still having trouble with the latest and greatest, please do let us know!
